/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorDetalle;
import Controlador.ControladorFactura;
import Controlador.ControladorProducto;
import Controlador.ControladorUsuario;
import Modelo.Detalle;
import Modelo.Factura;
import Modelo.Producto;
import Modelo.Usuario;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.Document;

/**
 *
 * @author VINICIO
 */
public class VistaFactura extends javax.swing.JInternalFrame {

    private Usuario usuarioAux;
    private ControladorUsuario controladorUsuario;
    private ControladorProducto controladorProducto;
    private ControladorDetalle controladorDetalle;
    private ControladorFactura controladorFactura;

    public VistaFactura() {
        initComponents();
        usuarioAux = null;
        controladorUsuario = new ControladorUsuario();
        controladorProducto = new ControladorProducto();
        controladorDetalle = new ControladorDetalle();
        controladorFactura = new ControladorFactura();

        Date date = new Date();
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        txtFecha.setText(dateFormat.format(date));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel25 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtTotalFactura = new javax.swing.JTextField();
        txtIVA = new javax.swing.JTextField();
        txtSubtotal = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnGuardarFactura = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaDetalle = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        buscar1 = new javax.swing.JButton();
        panelBuscarCliente = new javax.swing.JPanel();
        nombre2 = new javax.swing.JLabel();
        apillido2 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txtApellidoB = new javax.swing.JTextField();
        txtNombreB = new javax.swing.JTextField();
        txtTelefonoB = new javax.swing.JTextField();
        telefono2 = new javax.swing.JLabel();
        direcion2 = new javax.swing.JLabel();
        txtDirecionB = new javax.swing.JTextField();
        txtCorreoB = new javax.swing.JTextField();
        direcion4 = new javax.swing.JLabel();
        txtRolB = new javax.swing.JTextField();
        direcion3 = new javax.swing.JLabel();
        ingreseCedula = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        buscar2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        ingreseCedula1 = new javax.swing.JLabel();
        txtBuscar1 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaProduto = new javax.swing.JTable();
        checkproveedor = new javax.swing.JCheckBox();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaFacturas = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        tablaDetalleL = new javax.swing.JTable();
        jLabel24 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("CRUD Factura");

        jLabel25.setFont(new java.awt.Font("Sitka Heading", 2, 24)); // NOI18N
        jLabel25.setText("CONTROLADOR FACTURA");

        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/factura.png"))); // NOI18N

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtTotalFactura.setEditable(false);
        txtTotalFactura.setText("0");

        txtIVA.setEditable(false);
        txtIVA.setText("0");
        txtIVA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIVAActionPerformed(evt);
            }
        });

        txtSubtotal.setEditable(false);
        txtSubtotal.setText("0");

        jLabel12.setText("SUBTOTAL");

        jLabel13.setText("IVA 12%");

        jLabel14.setText("TOTAL A PAGAR");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTotalFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(txtIVA, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addGap(27, 27, 27))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addGap(3, 3, 3)
                .addComponent(txtIVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTotalFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        btnGuardarFactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar.png"))); // NOI18N
        btnGuardarFactura.setText("GUARDAR FACTURA");
        btnGuardarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarFacturaActionPerformed(evt);
            }
        });

        tablaDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "DESCRIPCION", "CANTIDAD", "PRECIO", "SUBTOTAL"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablaDetalle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tablaDetalleKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(tablaDetalle);

        jLabel9.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 255));
        jLabel9.setText("DETALLE");

        buscar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-login-50.png"))); // NOI18N
        buscar1.setText("AGREGAR PRODUCTO");
        buscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscar1ActionPerformed(evt);
            }
        });

        panelBuscarCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        nombre2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        nombre2.setText("NOMBRE: ");

        apillido2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        apillido2.setText("APELLIDOS: ");

        jLabel30.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N

        txtApellidoB.setEditable(false);

        txtNombreB.setEditable(false);

        txtTelefonoB.setEditable(false);

        telefono2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        telefono2.setText("TELEFONO:");

        direcion2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        direcion2.setText("DIRECCION");

        txtDirecionB.setEditable(false);

        txtCorreoB.setEditable(false);

        direcion4.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        direcion4.setText("ROL");

        txtRolB.setEditable(false);
        txtRolB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRolBActionPerformed(evt);
            }
        });

        direcion3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        direcion3.setText("CORREO");

        ingreseCedula.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        ingreseCedula.setText("INGRESE CEDULA: ");

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarKeyTyped(evt);
            }
        });

        buscar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
        buscar2.setText("BUSCAR");
        buscar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscar2ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("FECHA: ");

        txtFecha.setEditable(false);

        javax.swing.GroupLayout panelBuscarClienteLayout = new javax.swing.GroupLayout(panelBuscarCliente);
        panelBuscarCliente.setLayout(panelBuscarClienteLayout);
        panelBuscarClienteLayout.setHorizontalGroup(
            panelBuscarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscarClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBuscarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBuscarClienteLayout.createSequentialGroup()
                        .addComponent(ingreseCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(buscar2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelBuscarClienteLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(txtNombreB, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(direcion2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDirecionB, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(direcion4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtRolB, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBuscarClienteLayout.createSequentialGroup()
                        .addGroup(panelBuscarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelBuscarClienteLayout.createSequentialGroup()
                                .addComponent(nombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtApellidoB, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(direcion3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCorreoB, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(telefono2))
                            .addComponent(apillido2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTelefonoB, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelBuscarClienteLayout.setVerticalGroup(
            panelBuscarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscarClienteLayout.createSequentialGroup()
                .addGroup(panelBuscarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBuscarClienteLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(ingreseCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBuscarClienteLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBuscarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buscar2)
                        .addComponent(jLabel7)
                        .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panelBuscarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre2)
                    .addComponent(txtNombreB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(direcion2)
                    .addComponent(txtDirecionB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(direcion4)
                    .addComponent(txtRolB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelBuscarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apillido2)
                    .addComponent(txtApellidoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCorreoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(direcion3)
                    .addComponent(telefono2)
                    .addComponent(txtTelefonoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jLabel30)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnEliminar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/garbage.png"))); // NOI18N
        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        ingreseCedula1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        ingreseCedula1.setText("BUSCAR PRODUCTO POR NOMBRE O CODIGO: ");

        txtBuscar1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscar1KeyReleased(evt);
            }
        });

        tablaProduto.setBackground(new java.awt.Color(204, 255, 255));
        tablaProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "CODIGO", "Nombre", "PRECIO", "STOCK", "GANANCIA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tablaProduto);

        checkproveedor.setText("A precio de proveedor");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBuscarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addGap(200, 200, 200)
                            .addComponent(checkproveedor)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ingreseCedula1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buscar1)
                            .addComponent(btnGuardarFactura))
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminar)
                        .addGap(45, 45, 45))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panelBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(checkproveedor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 43, Short.MAX_VALUE)
                        .addComponent(buscar1)
                        .addGap(37, 37, 37)
                        .addComponent(btnGuardarFactura))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ingreseCedula1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("CREAR", jPanel1);

        tablaFacturas.setBackground(new java.awt.Color(102, 255, 255));
        tablaFacturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nro. FACTURA", "CLIENTE", "TOTAL", "FECHA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaFacturas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaFacturasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaFacturas);

        tablaDetalleL.setBackground(new java.awt.Color(204, 255, 204));
        tablaDetalleL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "CODIGO", "CANTIDAD", "DESCRIPCION", "PRECIO", "SUBTOTAL"
            }
        ));
        tablaDetalleL.setEnabled(false);
        jScrollPane6.setViewportView(tablaDetalleL);

        jLabel24.setFont(new java.awt.Font("Sitka Display", 3, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 255));
        jLabel24.setText("LISTA DE FACTURAS");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(162, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("LISTAR", jPanel9);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarFacturaActionPerformed

        boolean bandera = true;

        if (usuarioAux == null) {
            bandera = false;
        }
        if (tablaDetalle.getRowCount() <= 0) {
            bandera = false;
        }
        if (bandera) {
            double subtotal = Double.parseDouble(txtSubtotal.getText());
            double iva = Double.parseDouble(txtIVA.getText());;
            double total = Double.parseDouble(txtTotalFactura.getText());;
            String fecha = txtFecha.getText();
            Usuario usuario = usuarioAux;
            Factura factura = new Factura(0, subtotal, iva, total, fecha, usuario);
            if (controladorFactura.ingresar(factura)) {
                for (int i = 0; i < tablaDetalle.getRowCount(); i++) {
                    int cantidad = Integer.parseInt(tablaDetalle.getValueAt(i, 2) + "");
                    double subtotald = Double.parseDouble(tablaDetalle.getValueAt(i, 4) + "");
                    Producto producto = controladorProducto.buscar(tablaDetalle.getValueAt(i, 0) + "");
                    Factura facturad = controladorFactura.buscarID(controladorDetalle.obtenerCodigo() + "");
                    Detalle detalle = new Detalle(0, cantidad, subtotald, producto, facturad);
                    if (controladorDetalle.ingresar(detalle)) {
                        producto.setStock(producto.getStock() - cantidad);
                        controladorProducto.actualizar(producto);
                    } else {
                        JOptionPane.showMessageDialog(this, "Error al Detalle");
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "Error al guardar");
            }
            limpiarTabla();
        } else {
            JOptionPane.showMessageDialog(this, "Por fabor buscar al cleinte o llenar la tabla de productos");
        }
    }//GEN-LAST:event_btnGuardarFacturaActionPerformed
    public void limpiarTabla() {
        DefaultTableModel modelo = (DefaultTableModel) tablaDetalle.getModel();
        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }
        txtNombreB.setText("");
        txtApellidoB.setText("");
        txtTelefonoB.setText("");
        txtDirecionB.setText("");
        txtRolB.setText("");
        txtCorreoB.setText("");
        txtBuscar.setText("");
        txtIVA.setText("");
        txtTotalFactura.setText("");
        txtSubtotal.setText("");
        usuarioAux = null;
    }

    public void limpiarTabladEl() {
        DefaultTableModel modelo = (DefaultTableModel) tablaDetalleL.getModel();
        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }
    }

    public void limpiarTablaFL() {
        DefaultTableModel modelo = (DefaultTableModel) tablaFacturas.getModel();
        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }
    }
    private void tablaFacturasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaFacturasMouseClicked
        List<Detalle> lista = controladorDetalle.listaDetalle(tablaFacturas.getValueAt(tablaFacturas.getSelectedRow(), 0) + "");
        limpiarTabladEl();
        if (lista.isEmpty() == false) {
            DefaultTableModel model = (DefaultTableModel) tablaDetalleL.getModel();
            int index = 0;
            for (Detalle u : lista) {
                model.insertRow(index, new Object[]{u.getId(), u.getCantidad(), u.getProducto().getNombre(), u.getProducto().getPrecio(), u.getSubtotal()});
                index++;
            }
        } else {
            JOptionPane.showMessageDialog(this, "LISTA VACIA", "DETALLE", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_tablaFacturasMouseClicked

    private void buscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscar1ActionPerformed
        if (tablaProduto.getSelectedRow() != -1) {
            String cod = "";
            int can = 0;
            try {
                cod = (String) tablaProduto.getValueAt(tablaProduto.getSelectedRow(), 0);
                Producto producto = controladorProducto.buscar(cod + "");

                if (producto != null) {
                    DefaultTableModel model = (DefaultTableModel) tablaDetalle.getModel();
                    boolean existe = true;
                    int row = model.getRowCount();
                    for (int i = 0; i < model.getRowCount(); i++) {

                        Producto p = controladorProducto.buscar(tablaDetalle.getValueAt(i, 0) + "");
                        if (p.getId() == producto.getId()) {
                            existe = false;
                            int pasa = JOptionPane.showConfirmDialog(this, "Ya existe el producto \n DESEA ACTUALIZAR LA CANTIDAD");
                            if (pasa == JOptionPane.OK_OPTION) {
                                existe = true;
                                row = i;
                                model.removeRow(i);
                            } else {
                                existe = false;
                            }
                        }
                    }
                    if (existe) {
                        int numero = 0;
                        boolean bandera = false;
                        do {
                            try {
                                numero = Integer.parseInt(JOptionPane.showInputDialog(this, "Ingrese Cantidad \n ACTUALMENTE Existen: " + producto.getStock()));
                                if (numero <= producto.getStock()) {
                                    bandera = true;
                                } else {
                                    javax.swing.JOptionPane.showMessageDialog(this, "INGRES UNA CANTIDAD MENOR A: " + producto.getStock());
                                }
                            } catch (NumberFormatException e) {
                                javax.swing.JOptionPane.showMessageDialog(this, "Solo se permiten numeros");
                                bandera = false;
                            }
                        } while (!bandera);
                        int cant = numero;
                        model = (DefaultTableModel) tablaDetalle.getModel();
                        double precio = producto.getPrecio() + ((producto.getPre_cliente() * producto.getPrecio()) / 100);
                        if (checkproveedor.isSelected()) {
                            precio = producto.getPrecio() + ((producto.getPre_proveedor() * producto.getPrecio()) / 100);
                        }
                        model.insertRow(model.getRowCount(), new Object[]{producto.getCodigo(), producto.getNombre(), cant, precio, (precio * cant)});

                        double suma = 0;
                        for (int i = 0; i < tablaDetalle.getRowCount(); i++) {
                            suma = suma + (double) tablaDetalle.getValueAt(i, 4);
                        }

                        txtSubtotal.setText(suma + "");
                        txtIVA.setText((suma * 0.12) + "");
                        txtTotalFactura.setText("" + ((suma * 0.12) + suma) + "");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "No existe el producto");
                }

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }

        } else {
            JOptionPane.showMessageDialog(this, "DEBE SELECIONAR UN PRODUCTO", "AGRAGAR PRODUCTO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buscar1ActionPerformed

    private void txtIVAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIVAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIVAActionPerformed

    private void tablaDetalleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablaDetalleKeyPressed

    }//GEN-LAST:event_tablaDetalleKeyPressed

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        if (jTabbedPane1.getSelectedIndex() == 1) {
            limpiarTablaFL();
            List<Factura> lista;
            lista = controladorFactura.listar();
            if (lista.isEmpty() == false) {
                DefaultTableModel model = (DefaultTableModel) tablaFacturas.getModel();
                int index = 0;
                for (Factura u : lista) {
                    model.insertRow(index, new Object[]{u.getId(), u.getUsuario().getNombre() + " " + u.getUsuario().getApellido(), u.getTotal(), u.getFecha()});
                    index++;
                }
            } else {
                JOptionPane.showMessageDialog(this, "LISTA VACIA", "USUARIO", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void txtBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyTyped
        if (evt.getKeyCode() != KeyEvent.VK_DELETE) {
            if (evt.getKeyChar() < '0' || evt.getKeyChar() > '9') {
                evt.consume();
            }
        }
    }//GEN-LAST:event_txtBuscarKeyTyped

    private void buscar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscar2ActionPerformed
        if (txtBuscar.getBackground() == Color.green) {

            String cedula = txtBuscar.getText();
            Usuario usuario;
            usuario = controladorUsuario.buscar(cedula);
            if (usuario != null) {
                txtNombreB.setText(usuario.getNombre());
                txtApellidoB.setText(usuario.getApellido());
                txtTelefonoB.setText(usuario.getTelefono());
                txtDirecionB.setText(usuario.getDireccion());
                txtRolB.setText(usuario.getRol());
                txtCorreoB.setText(usuario.getCorreo());
                usuarioAux = usuario;
            } else {
                txtNombreB.setText("");
                txtApellidoB.setText("");
                txtTelefonoB.setText("");
                txtDirecionB.setText("");
                txtRolB.setText("");
                txtCorreoB.setText("");
                txtBuscar.setText("");
                usuarioAux = null;
                JOptionPane.showMessageDialog(this, "USUARIO NO ENCOTRADO", "USUARIO", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Cedula Incorrecta");
        }
    }//GEN-LAST:event_buscar2ActionPerformed

    private void txtBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyPressed
        controladorUsuario.keyTypedCedula(txtBuscar, evt);
    }//GEN-LAST:event_txtBuscarKeyPressed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        controladorUsuario.keyReleesCedula(txtBuscar, evt);
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void txtRolBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRolBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRolBActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (tablaDetalle.getSelectedRow() != -1) {
            DefaultTableModel model = (DefaultTableModel) tablaDetalle.getModel();
            model.removeRow(tablaDetalle.getSelectedRow());
            tablaDetalle.setModel(model);
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione linea a eliminar");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtBuscar1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscar1KeyReleased
        tablaProduto.removeAll();
        List<Producto> lis;
        lis = controladorProducto.listarLike(txtBuscar1.getText() + "");
        List<Object[]> lista = new ArrayList<>();
        for (Producto li : lis) {
            Object[] lisAr = new Object[5];
            lisAr[0] = li.getCodigo();
            lisAr[1] = li.getNombre();
            lisAr[2] = li.getPrecio();
            lisAr[3] = li.getStock();
            double precio =  ((li.getPre_cliente() * li.getPrecio()) / 100);
            if (checkproveedor.isSelected()) {
                precio =  ((li.getPre_proveedor() * li.getPrecio()) / 100);
            }
            lisAr[4] = precio;
            lista.add(lisAr);
        }
        String nombrecolumnas[] = {"CODIGO", "NOMBRE", "PRECIO", "STOCK", "GANANCIA"};
        Object datos[][] = new Object[lista.size()][nombrecolumnas.length];

        for (int j = 0; j < lista.size(); j++) {
            datos[j][0] = lista.get(j)[0];
            datos[j][1] = lista.get(j)[1];
            datos[j][2] = lista.get(j)[2];
            datos[j][3] = lista.get(j)[3];
            datos[j][4] = lista.get(j)[4];
        }
        DefaultTableModel modelo = new DefaultTableModel(datos, nombrecolumnas);
        tablaProduto.setModel(modelo);
    }//GEN-LAST:event_txtBuscar1KeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apillido2;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardarFactura;
    private javax.swing.JButton buscar1;
    private javax.swing.JButton buscar2;
    private javax.swing.JCheckBox checkproveedor;
    private javax.swing.JLabel direcion2;
    private javax.swing.JLabel direcion3;
    private javax.swing.JLabel direcion4;
    private javax.swing.JLabel ingreseCedula;
    private javax.swing.JLabel ingreseCedula1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel nombre2;
    private javax.swing.JPanel panelBuscarCliente;
    private javax.swing.JTable tablaDetalle;
    private javax.swing.JTable tablaDetalleL;
    private javax.swing.JTable tablaFacturas;
    private javax.swing.JTable tablaProduto;
    private javax.swing.JLabel telefono2;
    private javax.swing.JTextField txtApellidoB;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtBuscar1;
    private javax.swing.JTextField txtCorreoB;
    private javax.swing.JTextField txtDirecionB;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtIVA;
    private javax.swing.JTextField txtNombreB;
    private javax.swing.JTextField txtRolB;
    private javax.swing.JTextField txtSubtotal;
    private javax.swing.JTextField txtTelefonoB;
    private javax.swing.JTextField txtTotalFactura;
    // End of variables declaration//GEN-END:variables
}
